baseURL = "https://bricoymadera.com/"
title = "Brico y Madera"
theme = "ananke"

enableRobotsTXT = true
enableEmoji = true
summaryLength = 30

buildFuture = false

[pagination]
  pagerSize = 10

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  herramientas = "/herramientas/:slug/"
  guias = "/guias/:slug/"
  proyectos = "/proyectos/:slug/"
  sobre-nosotros = "/:slug/"
  legal = "/legal/:slug/"

[outputs]
  home = ["HTML", "RSS"]

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = false
  [privacy.instagram]
    disable = true
  [privacy.x]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
