baseURL = "https://bricoymadera.com/"
locale = "es-es"
title = "Brico y Madera"
theme = "ananke"

enableRobotsTXT = true
enableEmoji = true
summaryLength = 30

buildFuture = false

[pagination]
  pagerSize = 10

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  herramientas = "/herramientas/:slug/"
  sobre-mi = "/:slug/"

[outputs]
  home = ["HTML", "RSS"]

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.x]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
