[es]
  locale = "es-es"
  label = "Español"
  direction = "ltr"
  weight = 1
  title = "Brico y Madera"

  [es.params]
    dateFormat = "2 January 2006"
    mainSections = ["herramientas", "guias", "proyectos"]
    description = "Blog de bricolaje y carpintería con madera. Tutoriales, guías y herramientas para trabajar la madera."
