[[main]]
  identifier = "inicio"
  name = "Inicio"
  url = "/"
  weight = 1

[[main]]
  identifier = "herramientas"
  name = "Herramientas"
  url = "/herramientas/"
  weight = 2

[[main]]
  identifier = "guias"
  name = "Guías"
  url = "/guias/"
  weight = 3

[[main]]
  identifier = "proyectos"
  name = "Proyectos"
  url = "/proyectos/"
  weight = 4

[[main]]
  identifier = "sobre-nosotros"
  name = "Sobre Nosotros"
  url = "/sobre-nosotros/"
  weight = 5

[[footer]]
  identifier = "aviso-legal"
  name = "Aviso Legal"
  url = "/legal/aviso-legal/"
  weight = 1

[[footer]]
  identifier = "politica-cookies"
  name = "Política de Cookies"
  url = "/legal/politica-cookies/"
  weight = 2

[[footer]]
  identifier = "politica-privacidad"
  name = "Política de Privacidad"
  url = "/legal/politica-privacidad/"
  weight = 3
